import React from 'react';

import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Main from '../components/Main';
import Rules from '../components/Rules';

export default function Home() {
	const [playerScore, setPlayerScore] = React.useState();
	return (
		<div className={styles.container}>
			<Head>
				<title>RPSLSGame</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
				<link
					href='https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:wght@600;700&display=swap'
					rel='stylesheet'
				/>
			</Head>
			<main>
				<Header setPlayerScore={setPlayerScore} playerScore={playerScore} />
				<Main setPlayerScore={setPlayerScore} />
				<Rules />
			</main>
		</div>
	);
}
